-- 잊기 전에 한 번 더 정답

-- 4-2
SELECT DISTINCT JOB
  FROM EMP;

-- 4-3
SELECT EMPNO AS EMPLOYEE_NO,
       ENAME AS EMPLOYEE_NAME,
       JOB,
       MGR AS MANAGER,
       HIREDATE,
       SAL AS SALARY,
       COMM AS COMMSSION,
       DEPTNO AS DEPARTMENT_NO
  FROM EMP
ORDER BY DEPTNO DESC, ENAME;
