-- 잊기 전에 한 번 더 정답

-- 15-1
--① 
CREATE USER PREV_HW
IDENTIFIED BY ORCL;

--② 
GRANT CREATE SESSION TO PREV_HW;

-- 15-2
GRANT SELECT ON EMP TO PREV_HW; 

GRANT SELECT ON DEPT TO PREV_HW; 

GRANT SELECT ON SALGRADE TO PREV_HW; 

-- 15-3
REVOKE SELECT ON SALGRADE FROM PREV_HW; 