-- 잊기 전에 한 번 더 정답

-- 13-1
--① 
CREATE TABLE EMPIDX
 AS SELECT * 
      FROM EMP;

--② 
CREATE INDEX IDX_EMPIDX_EMPNO 
    ON EMPIDX (EMPNO);
	     
--③
SELECT * 
  FROM USER_INDEXES 
 WHERE INDEX_NAME = 'IDX_EMPIDX_EMPNO';

-- 13-2
CREATE OR REPLACE VIEW EMPIDX_OVER15K 
    AS (SELECT EMPNO, ENAME, JOB, DEPTNO, 
               SAL, NVL2(COMM, 'O', 'X') AS COMM 
          FROM EMPIDX 
         WHERE SAL > 1500); 

-- 13-3
--①
CREATE TABLE DEPTSEQ
    AS SELECT * 
         FROM DEPT; 
	
--② 
CREATE SEQUENCE SEQ_DEPTSEQ 
   INCREMENT BY 1
   START WITH 1
   MAXVALUE 99
   MINVALUE 1
   NOCYCLE NOCACHE;
   
--③
INSERT INTO DEPTSEQ (DEPTNO, DNAME, LOC) 
VALUES (SEQ_DEPTSEQ.NEXTVAL, 'DATABASE', 'SEOUL');

INSERT INTO DEPTSEQ (DEPTNO, DNAME, LOC) 
VALUES (SEQ_DEPTSEQ.NEXTVAL, 'WEB', 'BUSAN');

INSERT INTO DEPTSEQ (DEPTNO, DNAME, LOC) 
VALUES (SEQ_DEPTSEQ.NEXTVAL, 'MOBILE', 'ILSAN');
