-- 연습 12-1
CREATE TABLE EMP_HW ( 
     EMPNO    NUMBER(4), 
     ENAME    VARCHAR2(10), 
     JOB      VARCHAR2(9), 
     MGR      NUMBER(4), 
     HIREDATE DATE, 
     SAL      NUMBER(7, 2), 
     COMM     NUMBER(7, 2), 
     DEPTNO   NUMBER(2) 
); 

-- 연습 12-2
ALTER TABLE EMP_HW 
  ADD BIGO VARCHAR2(20);

-- 연습 12-3
ALTER TABLE EMP_HW 
MODIFY BIGO VARCHAR2(30); 

-- 연습 12-4
ALTER TABLE EMP_HW 
RENAME COLUMN BIGO TO REMARK; 

-- 연습 12-5
INSERT INTO EMP_HW 
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, NULL 
  FROM EMP; 

-- 연습 12-6
DROP TABLE EMP_HW;